services:
  db:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=brevly
    volumes:
      - "./docker:/docker-entrypoint-initdb.d"
    networks:
      - brevly
      - db
    
  app:
    build: .
    depends_on:
      - db
    container_name: brevly-server
    restart: unless-stopped
    ports:
      - 3333:$PORT
    environment:
      - PORT=3333
      - DATABASE_URL=postgresql://docker:docker@db:5432/brevly
      - CLOUDFLARE_ACCESS_KEY_ID=$CLOUDFLARE_ACCESS_KEY_ID
      - CLOUDFLARE_SECRET_ACCESS_KEY=$CLOUDFLARE_SECRET_ACCESS_KEY
      - CLOUDFLARE_BUCKET=$CLOUDFLARE_BUCKET
      - CLOUDFLARE_ACCOUNT_ID=$CLOUDFLARE_ACCOUNT_ID
      - CLOUDFLARE_PUBLIC_URL=$CLOUDFLARE_PUBLIC_URL
    networks:
      - brevly

volumes:
  db:

networks:
  brevly:
    driver: bridge
  db:
    driver: bridge